# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Projects\Spring Serpent\Spring-Serpent\designer\MachineScreen.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MachineScreen(object):
    def setupUi(self, MachineScreen):
        MachineScreen.setObjectName("MachineScreen")
        MachineScreen.resize(1360, 768)
        self.verticalLayout = QtWidgets.QVBoxLayout(MachineScreen)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Header = QtWidgets.QStackedWidget(MachineScreen)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Header.sizePolicy().hasHeightForWidth())
        self.Header.setSizePolicy(sizePolicy)
        self.Header.setMinimumSize(QtCore.QSize(0, 100))
        self.Header.setStyleSheet("QFrame {\n"
"    background-color: rgba(235, 152, 78, 1);\n"
"}")
        self.Header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Header.setObjectName("Header")
        self.no_job_header = QtWidgets.QWidget()
        self.no_job_header.setStyleSheet("QWidget {\n"
"    background-color: rgba(235, 152, 78, 1);\n"
"}")
        self.no_job_header.setObjectName("no_job_header")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.no_job_header)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.home_button = QtWidgets.QPushButton(self.no_job_header)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.home_button.sizePolicy().hasHeightForWidth())
        self.home_button.setSizePolicy(sizePolicy)
        self.home_button.setMinimumSize(QtCore.QSize(200, 65))
        self.home_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.home_button.setStyleSheet("QPushButton {\n"
"    image: url(:/buttons/buttons/home_button.png);\n"
"    background-color: rgba(165, 165, 165, 1);\n"
"    border-radius: 10px;\n"
"    font: 20pt \"Segoe UI Semibold\" ;\n"
"    color: rgb(255, 251, 244);\n"
" }\n"
"QPushButton:pressed {\n"
"    background-color: rgba(165, 165, 165, .7);\n"
"}")
        self.home_button.setText("")
        self.home_button.setObjectName("home_button")
        self.horizontalLayout.addWidget(self.home_button)
        self.machine_header = QtWidgets.QLabel(self.no_job_header)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(48)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.machine_header.setFont(font)
        self.machine_header.setStyleSheet("color: rgb(255, 251, 244);")
        self.machine_header.setObjectName("machine_header")
        self.horizontalLayout.addWidget(self.machine_header, 0, QtCore.Qt.AlignHCenter)
        spacerItem = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.Header.addWidget(self.no_job_header)
        self.job_header = QtWidgets.QWidget()
        self.job_header.setStyleSheet("QWidget {\n"
"    background-color: rgba(235, 152, 78, 1);\n"
"}")
        self.job_header.setObjectName("job_header")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.job_header)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.back_button = QtWidgets.QPushButton(self.job_header)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.back_button.sizePolicy().hasHeightForWidth())
        self.back_button.setSizePolicy(sizePolicy)
        self.back_button.setMinimumSize(QtCore.QSize(200, 65))
        self.back_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.back_button.setStyleSheet("QPushButton {\n"
"    image: url(:/buttons/buttons/back_button.png);\n"
"    background-color: rgba(165, 165, 165, 1);\n"
"    border-radius: 10px;\n"
"    font: 20pt \"Segoe UI\";\n"
" }\n"
"QPushButton:pressed {\n"
"    background-color: rgba(165, 165, 165, .7);\n"
"}\n"
"font: 20pt \"Segoe UI\";")
        self.back_button.setText("")
        self.back_button.setObjectName("back_button")
        self.horizontalLayout_5.addWidget(self.back_button)
        self.machine_header_2 = QtWidgets.QLabel(self.job_header)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(48)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.machine_header_2.setFont(font)
        self.machine_header_2.setStyleSheet("color: rgb(255, 251, 244);")
        self.machine_header_2.setObjectName("machine_header_2")
        self.horizontalLayout_5.addWidget(self.machine_header_2, 0, QtCore.Qt.AlignHCenter)
        self.home_button_2 = QtWidgets.QPushButton(self.job_header)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.home_button_2.sizePolicy().hasHeightForWidth())
        self.home_button_2.setSizePolicy(sizePolicy)
        self.home_button_2.setMinimumSize(QtCore.QSize(200, 65))
        self.home_button_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.home_button_2.setStyleSheet("QPushButton {\n"
"    image: url(:/buttons/buttons/home_button.png);\n"
"    background-color: rgba(165, 165, 165, 1);\n"
"    border-radius: 10px;\n"
"    font: 20pt \"Segoe UI Semibold\" ;\n"
"    color: rgb(255, 251, 244);\n"
" }\n"
"QPushButton:pressed {\n"
"    background-color: rgba(165, 165, 165, .7);\n"
"}")
        self.home_button_2.setText("")
        self.home_button_2.setObjectName("home_button_2")
        self.horizontalLayout_5.addWidget(self.home_button_2)
        self.Header.addWidget(self.job_header)
        self.verticalLayout.addWidget(self.Header)
        self.Screen = QtWidgets.QWidget(MachineScreen)
        self.Screen.setStyleSheet("background-color: rgb(71, 79, 84);")
        self.Screen.setObjectName("Screen")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Screen)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(25)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.sys_controls_frame = QtWidgets.QFrame(self.Screen)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(65)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sys_controls_frame.sizePolicy().hasHeightForWidth())
        self.sys_controls_frame.setSizePolicy(sizePolicy)
        self.sys_controls_frame.setStyleSheet("color: rgb(255, 251, 244);")
        self.sys_controls_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.sys_controls_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.sys_controls_frame.setObjectName("sys_controls_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.sys_controls_frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.system_controls_header = QtWidgets.QLabel(self.sys_controls_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.system_controls_header.sizePolicy().hasHeightForWidth())
        self.system_controls_header.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.system_controls_header.setFont(font)
        self.system_controls_header.setStyleSheet("color: rgb(255, 251, 244);")
        self.system_controls_header.setObjectName("system_controls_header")
        self.verticalLayout_2.addWidget(self.system_controls_header, 0, QtCore.Qt.AlignHCenter)
        self.controls_frame = QtWidgets.QFrame(self.sys_controls_frame)
        self.controls_frame.setStyleSheet("color: rgb(255, 251, 244);")
        self.controls_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.controls_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.controls_frame.setObjectName("controls_frame")
        self.gridLayout = QtWidgets.QGridLayout(self.controls_frame)
        self.gridLayout.setObjectName("gridLayout")
        self.feed_rate_frame = QtWidgets.QFrame(self.controls_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.feed_rate_frame.sizePolicy().hasHeightForWidth())
        self.feed_rate_frame.setSizePolicy(sizePolicy)
        self.feed_rate_frame.setStyleSheet("QLabel #feed_rate_header{\n"
"    color: rgb(255, 251, 244);\n"
"}")
        self.feed_rate_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.feed_rate_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.feed_rate_frame.setObjectName("feed_rate_frame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.feed_rate_frame)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.feed_rate_header = QtWidgets.QLabel(self.feed_rate_frame)
        self.feed_rate_header.setStyleSheet("font: 20pt \"Segoe UI\" Bold;\n"
"color: rgb(255, 251, 244);")
        self.feed_rate_header.setObjectName("feed_rate_header")
        self.verticalLayout_6.addWidget(self.feed_rate_header, 0, QtCore.Qt.AlignHCenter)
        spacerItem1 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_6.addItem(spacerItem1)
        self.feed_rate = QtWidgets.QLabel(self.feed_rate_frame)
        self.feed_rate.setStyleSheet("font: 20pt \"Segoe UI\" Bold;\n"
"color: rgb(255, 251, 244);")
        self.feed_rate.setObjectName("feed_rate")
        self.verticalLayout_6.addWidget(self.feed_rate, 0, QtCore.Qt.AlignHCenter)
        spacerItem2 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_6.addItem(spacerItem2)
        self.feed_rate_slider = QtWidgets.QSlider(self.feed_rate_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.feed_rate_slider.sizePolicy().hasHeightForWidth())
        self.feed_rate_slider.setSizePolicy(sizePolicy)
        self.feed_rate_slider.setMinimumSize(QtCore.QSize(375, 75))
        self.feed_rate_slider.setStyleSheet("QSlider {\n"
"    width: 50px;\n"
"    height: 50px;\n"
"}")
        self.feed_rate_slider.setMaximum(150)
        self.feed_rate_slider.setPageStep(1)
        self.feed_rate_slider.setOrientation(QtCore.Qt.Horizontal)
        self.feed_rate_slider.setInvertedAppearance(False)
        self.feed_rate_slider.setObjectName("feed_rate_slider")
        self.verticalLayout_6.addWidget(self.feed_rate_slider, 0, QtCore.Qt.AlignHCenter)
        self.gridLayout.addWidget(self.feed_rate_frame, 0, 0, 1, 1)
        self.reset_frame = QtWidgets.QFrame(self.controls_frame)
        self.reset_frame.setStyleSheet("QPushButton {\n"
"    background-color: rgba(165, 165, 165, 1);\n"
"    border-radius: 10px;\n"
"    font: 20pt \"Segoe UI\";\n"
"    color: rgb(255, 251, 244);\n"
" }\n"
"QPushButton:pressed {\n"
"    background-color: rgba(165, 165, 165, .7);\n"
"}")
        self.reset_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.reset_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.reset_frame.setObjectName("reset_frame")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.reset_frame)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.reset_header = QtWidgets.QLabel(self.reset_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reset_header.sizePolicy().hasHeightForWidth())
        self.reset_header.setSizePolicy(sizePolicy)
        self.reset_header.setStyleSheet("font: 20pt \"Segoe UI\" Bold;\n"
"color: rgb(255, 251, 244);")
        self.reset_header.setObjectName("reset_header")
        self.verticalLayout_5.addWidget(self.reset_header, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        spacerItem3 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_5.addItem(spacerItem3)
        self.reset_button = QtWidgets.QPushButton(self.reset_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reset_button.sizePolicy().hasHeightForWidth())
        self.reset_button.setSizePolicy(sizePolicy)
        self.reset_button.setMinimumSize(QtCore.QSize(250, 50))
        self.reset_button.setMaximumSize(QtCore.QSize(160000, 16777215))
        self.reset_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.reset_button.setObjectName("reset_button")
        self.verticalLayout_5.addWidget(self.reset_button)
        spacerItem4 = QtWidgets.QSpacerItem(20, 70, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_5.addItem(spacerItem4)
        self.gridLayout.addWidget(self.reset_frame, 0, 1, 1, 1)
        self.jog_control_frame = QtWidgets.QFrame(self.controls_frame)
        self.jog_control_frame.setStyleSheet("QRadioButton {\n"
"    font: 15pt \"Segoe UI\" Bold;\n"
"    color: rgb(255, 251, 244);\n"
"}\n"
"color: rgb(255, 251, 244);")
        self.jog_control_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.jog_control_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.jog_control_frame.setObjectName("jog_control_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.jog_control_frame)
        self.verticalLayout_3.setSpacing(20)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.jog_control_header = QtWidgets.QLabel(self.jog_control_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.jog_control_header.sizePolicy().hasHeightForWidth())
        self.jog_control_header.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        self.jog_control_header.setFont(font)
        self.jog_control_header.setStyleSheet("")
        self.jog_control_header.setObjectName("jog_control_header")
        self.verticalLayout_3.addWidget(self.jog_control_header, 0, QtCore.Qt.AlignHCenter)
        self.none_jog = QtWidgets.QRadioButton(self.jog_control_frame)
        self.none_jog.setObjectName("none_jog")
        self.verticalLayout_3.addWidget(self.none_jog, 0, QtCore.Qt.AlignHCenter)
        self.spindle_jog = QtWidgets.QRadioButton(self.jog_control_frame)
        self.spindle_jog.setObjectName("spindle_jog")
        self.verticalLayout_3.addWidget(self.spindle_jog, 0, QtCore.Qt.AlignHCenter)
        self.zaxis_jog = QtWidgets.QRadioButton(self.jog_control_frame)
        self.zaxis_jog.setObjectName("zaxis_jog")
        self.verticalLayout_3.addWidget(self.zaxis_jog, 0, QtCore.Qt.AlignHCenter)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem5)
        self.gridLayout.addWidget(self.jog_control_frame, 1, 0, 1, 1)
        self.homing_frame = QtWidgets.QFrame(self.controls_frame)
        self.homing_frame.setStyleSheet("QPushButton {\n"
"    background-color: rgba(165, 165, 165, 1);\n"
"    border-radius: 10px;\n"
"    color: rgb(255, 251, 244);\n"
" }\n"
"QPushButton:pressed {\n"
"    background-color: rgba(165, 165, 165, .7);\n"
"}")
        self.homing_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.homing_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.homing_frame.setObjectName("homing_frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.homing_frame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.homing_header = QtWidgets.QLabel(self.homing_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.homing_header.sizePolicy().hasHeightForWidth())
        self.homing_header.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI 12")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.homing_header.setFont(font)
        self.homing_header.setStyleSheet("")
        self.homing_header.setObjectName("homing_header")
        self.verticalLayout_4.addWidget(self.homing_header, 0, QtCore.Qt.AlignHCenter)
        spacerItem6 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem6)
        self.home_spindle_button = QtWidgets.QPushButton(self.homing_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.home_spindle_button.sizePolicy().hasHeightForWidth())
        self.home_spindle_button.setSizePolicy(sizePolicy)
        self.home_spindle_button.setMinimumSize(QtCore.QSize(250, 50))
        self.home_spindle_button.setMaximumSize(QtCore.QSize(160000, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        self.home_spindle_button.setFont(font)
        self.home_spindle_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.home_spindle_button.setObjectName("home_spindle_button")
        self.verticalLayout_4.addWidget(self.home_spindle_button)
        spacerItem7 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem7)
        self.home_zaxis_button = QtWidgets.QPushButton(self.homing_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.home_zaxis_button.sizePolicy().hasHeightForWidth())
        self.home_zaxis_button.setSizePolicy(sizePolicy)
        self.home_zaxis_button.setMinimumSize(QtCore.QSize(250, 50))
        self.home_zaxis_button.setMaximumSize(QtCore.QSize(160000, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        self.home_zaxis_button.setFont(font)
        self.home_zaxis_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.home_zaxis_button.setObjectName("home_zaxis_button")
        self.verticalLayout_4.addWidget(self.home_zaxis_button)
        spacerItem8 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_4.addItem(spacerItem8)
        self.gridLayout.addWidget(self.homing_frame, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.controls_frame)
        self.job_button_frame = QtWidgets.QStackedWidget(self.sys_controls_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.job_button_frame.sizePolicy().hasHeightForWidth())
        self.job_button_frame.setSizePolicy(sizePolicy)
        self.job_button_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.job_button_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.job_button_frame.setObjectName("job_button_frame")
        self.no_job_button_frame = QtWidgets.QWidget()
        self.no_job_button_frame.setObjectName("no_job_button_frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.no_job_button_frame)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.load_job_button = QtWidgets.QPushButton(self.no_job_button_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.load_job_button.sizePolicy().hasHeightForWidth())
        self.load_job_button.setSizePolicy(sizePolicy)
        self.load_job_button.setMinimumSize(QtCore.QSize(450, 85))
        self.load_job_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.load_job_button.setStyleSheet("QPushButton {\n"
"    background-color: rgba(52, 152, 219, 1);\n"
"    border-radius: 10px;\n"
"    font: 20pt \"Segoe UI\";\n"
"    color: rgb(255, 251, 244);\n"
" }\n"
"QPushButton:pressed {\n"
"    background-color: rgba(52, 152, 219, .7);\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: rgba(52, 152, 219, .7);\n"
"}")
        self.load_job_button.setObjectName("load_job_button")
        self.horizontalLayout_4.addWidget(self.load_job_button)
        self.job_button_frame.addWidget(self.no_job_button_frame)
        self.job_button_frame_2 = QtWidgets.QWidget()
        self.job_button_frame_2.setObjectName("job_button_frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.job_button_frame_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.start_job_button = QtWidgets.QPushButton(self.job_button_frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_job_button.sizePolicy().hasHeightForWidth())
        self.start_job_button.setSizePolicy(sizePolicy)
        self.start_job_button.setMinimumSize(QtCore.QSize(370, 85))
        self.start_job_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.start_job_button.setStyleSheet("QPushButton {\n"
"    background-color: rgba(46, 204, 113, 1);\n"
"    border-radius: 10px;\n"
"    font: 20pt \"Segoe UI\";\n"
"    color: rgb(255, 251, 244);\n"
" }\n"
"QPushButton:pressed {\n"
"    background-color: rgba(46, 204, 113, .7);\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: rgba(46, 204, 113, .7);\n"
"}")
        self.start_job_button.setObjectName("start_job_button")
        self.horizontalLayout_3.addWidget(self.start_job_button)
        self.stop_job_button = QtWidgets.QPushButton(self.job_button_frame_2)
        self.stop_job_button.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop_job_button.sizePolicy().hasHeightForWidth())
        self.stop_job_button.setSizePolicy(sizePolicy)
        self.stop_job_button.setMinimumSize(QtCore.QSize(370, 85))
        self.stop_job_button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.stop_job_button.setStyleSheet("QPushButton {\n"
"    background-color: rgba(231, 76, 60, 1);\n"
"    border-radius: 10px;\n"
"    font: 20pt \"Segoe UI\";\n"
"    color: rgb(255, 251, 244);\n"
" }\n"
"QPushButton:pressed {\n"
"    background-color: rgba(231, 76, 60, .7);\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: rgba(231, 76, 60, .7);\n"
"}")
        self.stop_job_button.setObjectName("stop_job_button")
        self.horizontalLayout_3.addWidget(self.stop_job_button)
        self.job_button_frame.addWidget(self.job_button_frame_2)
        self.verticalLayout_2.addWidget(self.job_button_frame)
        self.horizontalLayout_2.addWidget(self.sys_controls_frame)
        self.line = QtWidgets.QFrame(self.Screen)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.sys_status_frame = QtWidgets.QFrame(self.Screen)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(35)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sys_status_frame.sizePolicy().hasHeightForWidth())
        self.sys_status_frame.setSizePolicy(sizePolicy)
        self.sys_status_frame.setStyleSheet("QLabel {\n"
"    color: rgb(255, 251, 244);\n"
"}")
        self.sys_status_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.sys_status_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.sys_status_frame.setObjectName("sys_status_frame")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.sys_status_frame)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.sys_status_header = QtWidgets.QLabel(self.sys_status_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sys_status_header.sizePolicy().hasHeightForWidth())
        self.sys_status_header.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(24)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.sys_status_header.setFont(font)
        self.sys_status_header.setStyleSheet("color: rgb(255, 251, 244);")
        self.sys_status_header.setObjectName("sys_status_header")
        self.verticalLayout_7.addWidget(self.sys_status_header, 0, QtCore.Qt.AlignHCenter)
        self.sys_state_frame = QtWidgets.QFrame(self.sys_status_frame)
        self.sys_state_frame.setStyleSheet("QLabel {\n"
"    color: rgb(255, 251, 244);\n"
"}")
        self.sys_state_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.sys_state_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.sys_state_frame.setObjectName("sys_state_frame")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.sys_state_frame)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.sys_state_header = QtWidgets.QLabel(self.sys_state_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sys_state_header.sizePolicy().hasHeightForWidth())
        self.sys_state_header.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.sys_state_header.setFont(font)
        self.sys_state_header.setStyleSheet("QLabel {\n"
"    color: rgb(255, 251, 244);\n"
"}")
        self.sys_state_header.setObjectName("sys_state_header")
        self.verticalLayout_8.addWidget(self.sys_state_header, 0, QtCore.Qt.AlignHCenter)
        self.sys_state = QtWidgets.QLabel(self.sys_state_frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        self.sys_state.setFont(font)
        self.sys_state.setStyleSheet("QLabel {\n"
"    color: rgb(255, 251, 244);\n"
"    border: 2px solid rgb(255, 251, 244);\n"
"    background-color: rgb(0, 170, 127);\n"
"}")
        self.sys_state.setAlignment(QtCore.Qt.AlignCenter)
        self.sys_state.setObjectName("sys_state")
        self.verticalLayout_8.addWidget(self.sys_state)
        self.verticalLayout_7.addWidget(self.sys_state_frame)
        self.spindle_speed_frame = QtWidgets.QFrame(self.sys_status_frame)
        self.spindle_speed_frame.setStyleSheet("")
        self.spindle_speed_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.spindle_speed_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.spindle_speed_frame.setObjectName("spindle_speed_frame")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.spindle_speed_frame)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.spindle_speed_header = QtWidgets.QLabel(self.spindle_speed_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spindle_speed_header.sizePolicy().hasHeightForWidth())
        self.spindle_speed_header.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.spindle_speed_header.setFont(font)
        self.spindle_speed_header.setStyleSheet("QLabel {\n"
"    color: rgb(255, 251, 244);\n"
"}")
        self.spindle_speed_header.setObjectName("spindle_speed_header")
        self.verticalLayout_9.addWidget(self.spindle_speed_header, 0, QtCore.Qt.AlignHCenter)
        self.spindle_speed = QtWidgets.QLabel(self.spindle_speed_frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        self.spindle_speed.setFont(font)
        self.spindle_speed.setStyleSheet("QLabel {\n"
"    color: rgb(255, 251, 244);\n"
"    border: 2px solid rgb(255, 251, 244);\n"
"    text-align: center;\n"
"}")
        self.spindle_speed.setAlignment(QtCore.Qt.AlignCenter)
        self.spindle_speed.setObjectName("spindle_speed")
        self.verticalLayout_9.addWidget(self.spindle_speed)
        self.verticalLayout_7.addWidget(self.spindle_speed_frame)
        self.zaxis_speed_frame = QtWidgets.QFrame(self.sys_status_frame)
        self.zaxis_speed_frame.setStyleSheet("")
        self.zaxis_speed_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.zaxis_speed_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.zaxis_speed_frame.setObjectName("zaxis_speed_frame")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.zaxis_speed_frame)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.zaxis_speed_header = QtWidgets.QLabel(self.zaxis_speed_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zaxis_speed_header.sizePolicy().hasHeightForWidth())
        self.zaxis_speed_header.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.zaxis_speed_header.setFont(font)
        self.zaxis_speed_header.setStyleSheet("color: rgb(255, 251, 244);")
        self.zaxis_speed_header.setObjectName("zaxis_speed_header")
        self.verticalLayout_10.addWidget(self.zaxis_speed_header, 0, QtCore.Qt.AlignHCenter)
        self.zaxis_speed = QtWidgets.QLabel(self.zaxis_speed_frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        self.zaxis_speed.setFont(font)
        self.zaxis_speed.setStyleSheet("QLabel {\n"
"    color: rgb(255, 251, 244);\n"
"    border: 2px solid rgb(255, 251, 244);\n"
"    text-align: center;\n"
"}")
        self.zaxis_speed.setAlignment(QtCore.Qt.AlignCenter)
        self.zaxis_speed.setObjectName("zaxis_speed")
        self.verticalLayout_10.addWidget(self.zaxis_speed)
        self.verticalLayout_7.addWidget(self.zaxis_speed_frame)
        self.spindle_pos_frame = QtWidgets.QFrame(self.sys_status_frame)
        self.spindle_pos_frame.setStyleSheet("")
        self.spindle_pos_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.spindle_pos_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.spindle_pos_frame.setObjectName("spindle_pos_frame")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.spindle_pos_frame)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.spindle_pos_header = QtWidgets.QLabel(self.spindle_pos_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spindle_pos_header.sizePolicy().hasHeightForWidth())
        self.spindle_pos_header.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.spindle_pos_header.setFont(font)
        self.spindle_pos_header.setStyleSheet("color: rgb(255, 251, 244);")
        self.spindle_pos_header.setObjectName("spindle_pos_header")
        self.verticalLayout_11.addWidget(self.spindle_pos_header, 0, QtCore.Qt.AlignHCenter)
        self.spindle_position = QtWidgets.QLabel(self.spindle_pos_frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        self.spindle_position.setFont(font)
        self.spindle_position.setStyleSheet("QLabel {\n"
"    color: rgb(255, 251, 244);\n"
"    border: 2px solid rgb(255, 251, 244);\n"
"    text-align: center;\n"
"}")
        self.spindle_position.setAlignment(QtCore.Qt.AlignCenter)
        self.spindle_position.setObjectName("spindle_position")
        self.verticalLayout_11.addWidget(self.spindle_position)
        self.verticalLayout_7.addWidget(self.spindle_pos_frame)
        self.zaxis_pos_frame = QtWidgets.QFrame(self.sys_status_frame)
        self.zaxis_pos_frame.setStyleSheet("")
        self.zaxis_pos_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.zaxis_pos_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.zaxis_pos_frame.setObjectName("zaxis_pos_frame")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.zaxis_pos_frame)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.zaxis_pos_header = QtWidgets.QLabel(self.zaxis_pos_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zaxis_pos_header.sizePolicy().hasHeightForWidth())
        self.zaxis_pos_header.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.zaxis_pos_header.setFont(font)
        self.zaxis_pos_header.setStyleSheet("color: rgb(255, 251, 244);")
        self.zaxis_pos_header.setObjectName("zaxis_pos_header")
        self.verticalLayout_12.addWidget(self.zaxis_pos_header, 0, QtCore.Qt.AlignHCenter)
        self.zaxis_position = QtWidgets.QLabel(self.zaxis_pos_frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        self.zaxis_position.setFont(font)
        self.zaxis_position.setStyleSheet("QLabel {\n"
"    color: rgb(255, 251, 244);\n"
"    border: 2px solid rgb(255, 251, 244);\n"
"    text-align: center;\n"
"}")
        self.zaxis_position.setAlignment(QtCore.Qt.AlignCenter)
        self.zaxis_position.setObjectName("zaxis_position")
        self.verticalLayout_12.addWidget(self.zaxis_position)
        self.verticalLayout_7.addWidget(self.zaxis_pos_frame)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_7.addItem(spacerItem9)
        self.horizontalLayout_2.addWidget(self.sys_status_frame)
        self.verticalLayout.addWidget(self.Screen)

        self.retranslateUi(MachineScreen)
        self.Header.setCurrentIndex(0)
        self.job_button_frame.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MachineScreen)

    def retranslateUi(self, MachineScreen):
        _translate = QtCore.QCoreApplication.translate
        MachineScreen.setWindowTitle(_translate("MachineScreen", "Form"))
        self.machine_header.setText(_translate("MachineScreen", "Machine"))
        self.machine_header_2.setText(_translate("MachineScreen", "Machine"))
        self.system_controls_header.setText(_translate("MachineScreen", "System Controls"))
        self.feed_rate_header.setText(_translate("MachineScreen", "Feed Rate"))
        self.feed_rate.setText(_translate("MachineScreen", "0%"))
        self.reset_header.setText(_translate("MachineScreen", "Reset"))
        self.reset_button.setText(_translate("MachineScreen", "Reset Machine"))
        self.jog_control_header.setText(_translate("MachineScreen", "Jog Controller"))
        self.none_jog.setText(_translate("MachineScreen", "None"))
        self.spindle_jog.setText(_translate("MachineScreen", "Spindle"))
        self.zaxis_jog.setText(_translate("MachineScreen", "Z-Axis"))
        self.homing_header.setText(_translate("MachineScreen", "Homing"))
        self.home_spindle_button.setText(_translate("MachineScreen", "Home Spindle"))
        self.home_zaxis_button.setText(_translate("MachineScreen", "Home Z-Axis"))
        self.load_job_button.setText(_translate("MachineScreen", "Load Job"))
        self.start_job_button.setText(_translate("MachineScreen", "Start Job"))
        self.stop_job_button.setText(_translate("MachineScreen", "Stop Job"))
        self.sys_status_header.setText(_translate("MachineScreen", "System Status"))
        self.sys_state_header.setText(_translate("MachineScreen", "System State"))
        self.sys_state.setText(_translate("MachineScreen", "Running (65%)"))
        self.spindle_speed_header.setText(_translate("MachineScreen", "Spindle Speed"))
        self.spindle_speed.setText(_translate("MachineScreen", "- RPM"))
        self.zaxis_speed_header.setText(_translate("MachineScreen", "Z-Axis Speed"))
        self.zaxis_speed.setText(_translate("MachineScreen", "- RPM"))
        self.spindle_pos_header.setText(_translate("MachineScreen", "Spindle Position"))
        self.spindle_position.setText(_translate("MachineScreen", "-"))
        self.zaxis_pos_header.setText(_translate("MachineScreen", "Z-Axis Position"))
        self.zaxis_position.setText(_translate("MachineScreen", "-"))
from . import Spring_Serpent_Resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MachineScreen = QtWidgets.QWidget()
    ui = Ui_MachineScreen()
    ui.setupUi(MachineScreen)
    MachineScreen.show()
    sys.exit(app.exec_())
